
const datas = [
        {
          id: "10000",
          parentId: null,
          name: "  10000",
          size: "53k",
          type: "",
          date: "2019-10-22",
          checked: false,
          indeterminate: false,
          childCols: [],
          childData: [],
          hasChild: true,
          children: [
            {
              id: "11000",
              parentId: "10000",
              name: " 123",
              size: "11k",
              type: "avi",
              date: "2019-05-21",
              checked: false,
              indeterminate: false,
              childCols: [],
              childData: [],
            },
            {
              id: "12000",
              parentId: "10000",
              name: "文件夹 12000",
              size: "22k",
              type: "",
              date: "2019-08-16",
              childCols: [],
              childData: [],
              checked: false,
              indeterminate: false,
              hasChild: true,
              children: [
                {
                  id: "12100",
                  parentId: "12000",
                  name: "  12100.png",
                  size: "60k",
                  type: "",
                  date: "2019-08-20",
                  childCols: [],
                  childData: [],
                  checked: false,
                  indeterminate: false,
                  hasChild: true,
                  children: [
                    {
                      id: "12110",
                      parentId: "12100",
                      name: "某个页面 12110.html",
                      size: "100k",
                      type: "html",
                      date: "2019-05-19",
                      childCols: [],
                      childData: [],
                      checked: false,
                      indeterminate: false,
                    },
                  ],
                },
                {
                  id: "122000",
                  parentId: "12000",
                  name: "xxx 122000123",
                  size: "80k",
                  type: "avi",
                  date: "2019-04-18",
                  childCols: [],
                  childData: [],
                  checked: false,
                  indeterminate: false,
                },
                {
                  id: "123000",
                  parentId: "12000",
                  name: "文件夹 123000",
                  size: "",
                  type: "",
                  date: "2019-06-17",
                  childCols: [],
                  childData: [],
                  checked: false,
                  indeterminate: false,
                  hasChild: true,
                  children: [
                    {
                      id: "123100",
                      parentId: "123000",
                      name: "  123100123",
                      size: "105k",
                      type: "avi",
                      date: "2019-05-16",
                      childCols: [],
                      childData: [],
                      checked: false,
                      indeterminate: false,
                    },
                    {
                      id: "123200",
                      parentId: "123000",
                      name: "文件 123200123",
                      size: "105k",
                      type: "avi",
                      date: "2019-02-20",
                      childCols: [],
                      childData: [],
                      checked: false,
                      indeterminate: false,
                    },
                    {
                      id: "123300",
                      parentId: "123000",
                      name: "  123300.txt",
                      size: "18k",
                      type: "txt",
                      date: "2019-04-21",
                      childCols: [],
                      childData: [],
                      checked: false,
                      indeterminate: false,
                    },
                  ],
                },
                {
                  id: "124000",
                  parentId: "12000",
                  name: " 124000.mp4",
                  size: "860k",
                  type: "mp4",
                  date: "2019-01-27",
                  childCols: [],
                  childData: [],
                  checked: false,
                  indeterminate: false,
                },
                {
                  id: "125000",
                  parentId: "12000",
                  name: " 125000123",
                  size: "660k",
                  type: "avi",
                  date: "2019-09-12",
                  childCols: [],
                  childData: [],
                  checked: false,
                  indeterminate: false,
                },
                {
                  id: "126000",
                  parentId: "12000",
                  name: " 126000123",
                  size: "320k",
                  type: "avi",
                  date: "2019-07-29",
                  childCols: [],
                  childData: [],
                  checked: false,
                  indeterminate: false,
                },
              ],
            },
          ],
        },
        {
          id: "20000",
          parentId: null,
          name: " 20000",
          size: "66k",
          type: "png",
          date: "2019-08-23",
          childCols: [],
          childData: [],
          checked: false,
          indeterminate: false,
        },
        {
          id: "30000",
          parentId: null,
          name: "30000",
          size: "3k",
          type: "",
          date: "2019-05-14",
          childCols: [],
          childData: [],
          checked: false,
          indeterminate: false,
          hasChild: true,
          children: [
            {
              id: "31000",
              parentId: "30000",
              name: "31000",
              size: "9k",
              type: "",
              date: "2019-07-24",
              childCols: [],
              childData: [],
              checked: false,
              indeterminate: false,
              hasChild: true,
              children: [
                {
                  id: "31100",
                  parentId: "31000",
                  name: " 31100.js",
                  size: "40k",
                  type: "js",
                  date: "2019-05-27",
                  childCols: [],
                  childData: [],
                  checked: false,
                  indeterminate: false,
                },
                {
                  id: "31200",
                  parentId: "31000",
                  name: "文件 31200",
                  size: "224k",
                  type: "java",
                  date: "2019-10-25",
                  childCols: [],
                  childData: [],
                  checked: false,
                  indeterminate: false,
                },
              ],
            },
            {
              id: "32000",
              parentId: "30000",
              name: "文件夹 32000",
              size: "33k",
              type: "",
              date: "2019-05-25",
              childCols: [],
              childData: [],
              checked: false,
              indeterminate: false,
              hasChild: true,
              children: [
                {
                  id: "32100",
                  parentId: "32000",
                  name: "  32100.mp4",
                  size: "35k",
                  type: "mp4",
                  date: "2019-05-28",
                  childCols: [],
                  childData: [],
                  checked: false,
                  indeterminate: false,
                },
                {
                  id: "32200",
                  parentId: "32000",
                  name: "文件夹 32000",
                  size: "33k",
                  type: "",
                  date: "2019-02-29",
                  childCols: [],
                  childData: [],
                  checked: false,
                  indeterminate: false,
                  hasChild: true,
                  children: [
                    {
                      id: "32210",
                      parentId: "32200",
                      name: " 从入门到住院 32210.pdf",
                      size: "75k",
                      type: "pdf",
                      date: "2019-12-13",
                      childCols: [],
                      childData: [],
                      checked: false,
                      indeterminate: false,
                    },
                    {
                      id: "32220",
                      parentId: "32200",
                      name: "文件夹 32220",
                      size: "33k",
                      type: "",
                      date: "2019-08-12",
                      childCols: [],
                      childData: [],
                      checked: false,
                      indeterminate: false,
                      hasChild: true,
                      children: [
                        {
                          id: "32221",
                          parentId: "32220",
                          name: "  32221.pdf",
                          size: "85k",
                          type: "pdf",
                          date: "2019-12-30",
                          childCols: [],
                          childData: [],
                          checked: false,
                          indeterminate: false,
                        },
                        {
                          id: "32222",
                          parentId: "32220",
                          name: " 从入门到住院 32222.ppt",
                          size: "998k",
                          type: "ppt",
                          date: "2019-10-30",
                          childCols: [],
                          childData: [],
                          checked: false,
                          indeterminate: false,
                        },
                        {
                          id: "32223",
                          parentId: "32220",
                          name: " 32223.xlsx",
                          size: "95k",
                          type: "xlsx",
                          date: "2019-11-01",
                          childCols: [],
                          childData: [],
                          checked: false,
                          indeterminate: false,
                        },
                      ],
                    },
                  ],
                },
                {
                  id: "32300",
                  parentId: "32000",
                  name: "文件夹 32300",
                  size: "678k",
                  type: "",
                  date: "2019-01-10",
                  childCols: [],
                  childData: [],
                  checked: false,
                  indeterminate: false,
                  hasChild: true,
                  children: [
                    {
                      id: "32310",
                      parentId: "32300",
                      name: " 32310.mp4",
                      size: "75k",
                      type: "mp4",
                      date: "2019-11-09",
                      childCols: [],
                      childData: [],
                      checked: false,
                      indeterminate: false,
                    },
                    {
                      id: "32320",
                      parentId: "32300",
                      name: "文件夹 32320",
                      size: "88k",
                      type: "",
                      date: "2019-08-08",
                      childCols: [],
                      childData: [],
                      checked: false,
                      indeterminate: false,
                      hasChild: true,
                      children: [
                        {
                          id: "32321",
                          parentId: "32320",
                          name: "音乐 32321.mp3",
                          size: "5k",
                          type: "mp3",
                          date: "2019-03-07",
                          childCols: [],
                          childData: [],
                          checked: false,
                          indeterminate: false,
                        },
                        {
                          id: "32322",
                          parentId: "32320",
                          name: "在线观看 32322123",
                          size: "5k",
                          type: "avi",
                          date: "2019-09-09",
                          childCols: [],
                          childData: [],
                          checked: false,
                          indeterminate: false,
                        },
                        {
                          id: "32323",
                          parentId: "32320",
                          name: "音乐 32323.mp3",
                          size: "576k",
                          type: "mp3",
                          date: "2019-09-04",
                          childCols: [],
                          childData: [],
                          checked: false,
                          indeterminate: false,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              id: "33000",
              parentId: "30000",
              name: "在线文档 33000.txt",
              size: "95k",
              type: "txt",
              date: "2019-01-14",
              childCols: [],
              childData: [],
              checked: false,
              indeterminate: false,
            },
            {
              id: "34000",
              parentId: "30000",
              name: " 从入门到住院 34000123",
              size: "786k",
              type: "avi",
              date: "2019-01-17",
              childCols: [],
              childData: [],
              checked: false,
              indeterminate: false,
            },
            {
              id: "35000",
              parentId: "30000",
              name: "  35000.mp4",
              size: "286k",
              type: "mp4",
              date: "2019-02-19",
              childCols: [],
              childData: [],
              checked: false,
              indeterminate: false,
            },
            {
              id: "36000",
              parentId: "30000",
              name: "vue3.0 入门教程 36000.pdf",
              size: "870k",
              type: "pdf",
              date: "2019-12-27",
              childCols: [],
              childData: [],
              checked: false,
              indeterminate: false,
            },
          ],
        },
        {
          id: "40000",
          parentId: null,
          name: " 40000",
          size: "26k",
          type: "mp4",
          date: "2019-03-04",
          childCols: [],
          childData: [],
          checked: false,
          indeterminate: false,
          hasChild: true,
          children: [
            {
              id: "41000",
              parentId: "40000",
              name: "xxx 41000.mp4",
              size: "135k",
              type: "mp4",
              date: "2019-02-03",
              childCols: [],
              childData: [],
              checked: false,
              indeterminate: false,
            },
          ],
        },
        {
          id: "50000",
          parentId: null,
          name: "  50000123",
          size: "498k",
          type: "avi",
          date: "2019-12-02",
          childCols: [],
          childData: [],
          children: [],
          checked: false,
          indeterminate: false,
        },
      ]

export default datas
